---
- name: Installing mysql server
  hosts: all
  become: yes
  tasks:
    - name: Installing mysql 
      apt:
        update_cache: yes
        name: mysql-server
        state: present
    - name: Install python3-PyMySQL library
      apt:
        name: python3-pymysql
        state: present
    - name: update mysql root password for root account
      mysql_user:
        name: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: Testuser@123
        host: 'localhost'
        password: Testuser@123
        priv: "*.*:ALL,GRANT"
        check_implicit_admin: true
        state: present
    - name: Creating user 
      mysql_user:
        login_user: root
        login_password: Testuser@123
        name: spurtcommerce
        password: spurtcommerce
        host: '%'
        priv: "*.*:ALL,GRANT"
        state: present
    - name: Creating user 
      mysql_db:
        login_user: root
        login_password: Testuser@123
        name: spurtcommerce
        state: present
    
